### ISSUE TITLE
Backup/Restore notes with encryption

### ISSUE THREAD

**Issue by serrq** [dev-xero/paper-app#33]
I need of this feature.

**Comment by dev-xero** [comment]
I'm not planning on adding that feature but you can extend the app if you want to include it, I'll be happy to merge if it works

**Comment by serrq** [comment]
I am not a developer.

**Comment by dev-xero** [comment]
I see, but backing up to the cloud is not something I'm considering at the moment

**Comment by serrq** [comment]
I didn’t ask for backup on cloud. Local.

**Comment by dev-xero** [comment]
The notes are already saved locally

**Comment by serrq** [comment]
> The notes are already saved locally

Where are them? I mean in a convenient compact format like .zip.

**Comment by supernatural30** [comment]
I would also like to know where the files are stored. 

I looked under storage/emulated/0/Android on unrooted stock phone and couldn't find anything.

The ability to export a .json or .txt or .zip to local storage would be great.

**Comment by dev-xero** [comment]
It's a local DB stored on your device, you wouldn't be able to find it like that
