### ISSUE TITLE
Reorganize notes with filters or manually

### ISSUE THREAD

**Issue by serrq** [dev-xero/paper-app#36]
I would like have a way to sort the notes by a rule or by manually drag a tile and move it elsewhere.

**Comment by dev-xero** [comment]
I won't implement drag and drop yet, but sorting is being worked on

**Comment by serrq** [comment]
This is the current situation.


![1000001677](https://user-images.githubusercontent.com/113377431/226550100-c6a9c25f-2f2a-4c33-a873-a6ecdeead096.jpg)
