### ISSUE TITLE
make the cursor jump to "content" when area underneath is touched

### ISSUE THREAD

**Issue by SnoutBug** [dev-xero/paper-app#40]
It would be great if the cursor jumped to "content" if the area underneath the input box is touched. The missing borders of the input box imply that this is a valid area to be pressed

![Screenshot_20230322-153708](https://user-images.githubusercontent.com/71790678/226939234-57bdd2f3-34f5-4d87-aea5-839861acecd0.png)

**Comment by dev-xero** [comment]
Oh, nice! Added to what I'm working on
